### ISSUE TITLE
syntax error in './gsk-4.0/path_point.cr:122:13': can't use variable name 'center' inside assignment to variable 'center'

### ISSUE THREAD

**Issue by GeopJr** [hugopl/gi-crystal#144]
This is on 46beta, the generated code is:

```crystal
def curvature(path : Gsk::Path,direction : Gsk::PathDirection,) : Graphene::Point
  # gsk_path_point_get_curvature: (Method)
# @path: 
# @direction: 
# @center: (out) (nullable) (caller-allocates) 
# Returns: (transfer none) 

  
  # Generator::NullableArrayPlan
center = if center.nil?
Void.null
else
center.to_unsafe
end
# Generator::CallerAllocatesPlan
center=Graphene::Point.new
  # C call
  _retval = LibGsk.gsk_path_point_get_curvature(to_unsafe, path, direction, center)


  
  # Return value handling
  center

end
```

The order doesn't really make much sense as center gets overwritten afterwards anyway?

**Comment by GeopJr** [comment]
This is the same issue as the harfbuzz one some versions ago, I don't know if curvature should also be ignored

**Comment by GeopJr** [comment]
Closing as this has been fixed on gtk4.cr

**Comment by hugopl** [comment]
I think we can keep this open here, since gtk4 shard doesn't really fix it but just ignore the function.
